on: push
name: deploy
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - env:
        HOST: ${{ env.HOST }}
      run: |
        echo "host = ${{ env.HOST}}"
        echo "host = $(echo ${HOST} | base64)"
        
