on: push
name: deploy
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: catdockerfile
      uses: actions/checkout@v2.3.4
    - name: pwd
      run: echo ${{ secrets.SSHHOST }}
    - name: ls
      run: echo ${{ secrets.USERNAME }}
    - name: env
      run: echo ${{ secrets.PASSPHRASE }}
    - name: run on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSHHOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /root/compose/monorepo
          pwd
          docker compose up
      