on: push
name: deploy
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: ok
      uses: actions/checkout
      env:
        HOST: ${{ secrets.HOST }}
        run: |
          echo "host = ${HOST}"
          echo "host = $(echo ${HOST} | base64)"
        
