on: push
name: deploy
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "docker-compose.yaml"
        target: ${{ secrets.mono }}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      env:
        HOSTNAME: ${{ secrets.HOSTNAME }}
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: HOSTNAME
        script: |
          cd ${{ secrets.mono }}
          docker compose up -d

        
