on: push
name: deploy
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - env:
        HOST: ${{ secrets.HOSTNAME }}
      run: |
        echo "hostenv = ${{ env.HOSTNAME}}"
        echo "host secret 64 = $(echo ${HOSTNAME} | base64)"
        echo "host secret= echo ${HOSTNAME}"
        
