on: push
name: deploy
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: run on VPS
      uses: appleboy/ssh-action@master
      with:
        
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }} 
        PASSWORD: ${{ secrets.PASSPHRASE }}
        script: |
          whoami 
          ls
          cd /root/compose/monorepo
          pwd
          ls
          docker compose up